src/budget/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^registry/', include(r'registry.urls')),
    url(r'^', include(r'registry.urls')),
]

src/registry/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from . import views
from . import api_views

app_name = 'registry'


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^billings$', views.BillingsView.as_view(), name='billings'),
    url(r'^list_io$', views.ListIOView.as_view(), name='list_io'),
    url(r'^io/delete/(?P<id>\d+)/$', views.DeleteIOView.as_view(), name='delete_io'),
    url(r'^io/edit/(?P<id>\d+)/$', views.EditIOView.as_view(), name='edit_io'),
    url(r'^report$', views.ReportView.as_view(), name='report'),
    url(r'^report/view$', views.ReportViewView.as_view(), name='report_view'),
    url(r'^billing/view/(?P<id>\d+)/$', views.BillingView.as_view(), name='billing/view'),
    url(r'^import$', views.ImportIOView.as_view(), name='import')
]

apiurls = [
    url(r'^api/io/$', api_views.ApiIOVIew.as_view(), name='api-io'),
    url(r'^api/io/(?P<pk>[0-9]+)/$', api_views.ApiIOVIew.as_view(), name='api-io'),
    url(r'^api/io-simple/$', api_views.ApiIOSimpleView.as_view(), name='api-io-simple'),
    url(r'^api/category/$', api_views.ApiCategoryView.as_view(), name='api-category'),
    url(r'^api/payment-method/$', api_views.ApiPaymentMethodView.as_view(), name='api-payment-method'),
]

urlpatterns += format_suffix_patterns(apiurls)

src/registry/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

@python_2_unicode_compatible
class PaymentMethodModel(models.Model):
    name = models.CharField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'payment method'
        verbose_name_plural = 'payment methods'
    
    def __str__(self):
        return self.name


@python_2_unicode_compatible
class CategoryModel(models.Model):
    NAMESPACE_SEPARATOR = r'/'
    
    name = models.CharField(max_length=200, unique=True)
    
    class Meta:
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'
     
    def __str__(self):
        return self.name
    

@python_2_unicode_compatible
class IOModel(models.Model):
    INCOME = 'I'
    OUTCOME = 'O'
    TYPE_CHOICES = (
        (INCOME, 'Income'),
        (OUTCOME, 'Outcome')
    )
    
    category = models.ForeignKey(
        CategoryModel,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    payment_method = models.ForeignKey(
        PaymentMethodModel,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    name = models.CharField(max_length=200)
    type = models.CharField(max_length=1, choices=TYPE_CHOICES, default=OUTCOME)
    amount = models.DecimalField(max_digits=8, decimal_places=2, null=False)
    registered = models.DateTimeField()
    
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name


@python_2_unicode_compatible
class BillingCycleModel(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateField(unique=True)
    end_date = models.DateField(blank=True, null=True, unique=True)
    
    class Meta:
        ordering = ['start_date']
        verbose_name = 'billing cycle'
        verbose_name_plural = 'billing cycles'
        
    def __str__(self):
        return self.name

src/registry/forms.py
# vim: set fileencoding=utf-8 :

from django.forms import ModelForm
from models import IOModel, CategoryModel, PaymentMethodModel
from django.db.models.functions import Lower
from django import forms
import django_filters
# import datetime

class IOForm(ModelForm):
    class Meta:
        model = IOModel
        fields = ['name', 'type', 'amount', 'registered', 'category', 'payment_method']

    def __init__(self, *args, **kwargs):
        super(IOForm, self).__init__(*args, **kwargs)   
        self.fields['category'].queryset = CategoryModel.objects.order_by(Lower('name'))
        self.fields['payment_method'].queryset = PaymentMethodModel.objects.order_by(Lower('name'))
        self.fields['registered'].widget.format = '%Y-%m-%d'


# class ListIOFilterForm(forms.Form):
#     start_date = forms.DateField(required=False, label="Od")
#     end_date = forms.DateField(required=False, label="Do")
#     type = forms.ChoiceField(required=False, label="Typ")
#     category = forms.ModelChoiceField(required=False, queryset=CategoryModel.objects.all(), label="Kategoria")
#     
#     def __init__(self, *args, **kwargs):
#         self.label_suffix = ':'
#         
#         super(ListIOFilterForm, self).__init__(*args, **kwargs)
#         
#         self.fields['type'].choices = (('', '--------'),) + IOModel.TYPE_CHOICES
        
class ListIOFilter(django_filters.FilterSet):
    start_date = django_filters.DateFilter(lookup_type='gte', label="Od", help_text='', name='registered')
    end_date = django_filters.DateFilter(lookup_type='lte', label="Do", help_text='', name='registered')
    type = django_filters.ChoiceFilter(label="Typ", help_text='')
    category = django_filters.ModelChoiceFilter(queryset=CategoryModel.objects.all(), label="Kategoria", help_text='')
    payment_method = django_filters.ModelChoiceFilter(queryset=PaymentMethodModel.objects.all(), label="Płatność", help_text='')
    
    class Meta:
        model = IOModel
        fields = []
        
    def __init__(self, *args, **kwargs):
        super(ListIOFilter, self).__init__(*args, **kwargs)
        self.form.label_suffix = ':'
        self.form.fields['type'].choices = (('', '--------'),) + IOModel.TYPE_CHOICES

class ImportIOForm(forms.Form):
    io_file = forms.FileField(required=True, label="Plik csv z transakcjami")

    def __init__(self, *args, **kwargs):
        self.label_suffix = ':'

        super(ImportIOForm, self).__init__(*args, **kwargs)

src/registry/views.py
# -*- coding: utf-8 -*-

import datetime
import logging

from collections import OrderedDict, defaultdict

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import View
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.dateparse import parse_date

from .models import IOModel, CategoryModel, BillingCycleModel
from .forms import IOForm, ListIOFilter, ImportIOForm, PaymentMethodModel
from .reports import OverviewReport
from .import_parser import MBankCsvParser, MBANK_FILTERS

logger = logging.getLogger('django')
# class Referer(object):
# 	refererFieldName = 'referer'
# 	def __init__(self, request, default=None):
# 		self.__referer = request.session.pop( # removing it
# 			self.refererFieldName,
# 			request.POST.get(
# 				self.refererFieldName,
# 				request.GET.get(
# 					self.refererFieldName,
# 					request.META.get('HTTP_REFERER')
# 				)
# 			)
# 		)
# 		if self.__referer is None:
# 			self.__referer = default
# 
# 	def get(self):
# 		return self.__referer

class IndexView(View):
	def post(self, request):
		form = IOForm(request.POST)
		if form.is_valid():
			io = form.save()
			io.save()
			return HttpResponseRedirect(reverse('registry:index'))
		else:
			return render(request, r'registry/index.html', self._make_context_with_form(form))

	def get(self, request):
		context = self._make_context_with_form(IOForm())
		context.update({'import_form': ImportIOForm()})
		return render(
			request,
			r'registry/index.html',
			context
		)

	def _make_context_with_form(self, form):
		return {
			'form' : form,
			'ios' : IOModel.objects.order_by('-updated')[:10]
		}

class ImportIOView(View):
    def post(self, request):
        form = ImportIOForm(request.POST, request.FILES)
        if form.is_valid():
            data = MBankCsvParser().parse(request.FILES['io_file'])
            data = self._filter(data)
            return render(request, r'registry/import.html', dict(data=data, categories=CategoryModel.objects.all()))
        else:
            return render(request, r'registry/import.html', dict(error="Failed to import selected file."))

    def _filter(self, data):
        result = []
        for d in data:
            for filter in MBANK_FILTERS:
                d = filter(d)
                if d is None: break
            if d is not None:
                result.append(d)
        return result


class BillingsView(View):
	def get(self, request):
		billings = BillingCycleModel.objects.all().order_by('-start_date')
		report = None
		if len(billings) != 0:
			report = OverviewReport(billings[0].start_date, billings[0].end_date)
		return render(request, r'registry/billings.html', {'billings': billings, 'report': report})


class ListIOView(View):
	def get(self, request):
		filter = ListIOFilter(request.GET, queryset=IOModel.objects.all().order_by('registered'))
		query = request.GET.copy()
		ios = self.paginate(filter.qs, int(query.pop('page', [1])[-1]), 100)

		return render(request, r'registry/list_io.html', {'ios': ios, 'filter': filter, 'query': query})

# 	def post(self, request):
# 		filter = ListIOFilter(request.POST, queryset=IOModel.objects.all().order_by('registered'))
# 		ios = self.paginate(filter.qs, request.GET.get('page'))
# 		return render(request, r'registry/list_io.html', {'ios': ios, 'filter': filter})

	def paginate(self, queryset, page, pageSize):
		paginator = Paginator(queryset, pageSize)
		try:
			result = paginator.page(page)
		except PageNotAnInteger:
			result = paginator.page(1)
		except EmptyPage:
			result = paginator.page(paginator.num_pages)
		return result


class DeleteIOView(View):
	def get(self, request, id):
		answer = request.GET.get('answer')
		if answer:
			if answer == 'yes':
				IOModel.objects.get(pk=id).delete()
			return HttpResponseRedirect(request.session.pop('referer', reverse('registry:index')))
		else:
			request.session['referer'] = request.META.get('HTTP_REFERER', reverse('registry:index'))
			return render(request, r'registry/delete_io.html', {'io' : IOModel.objects.get(pk=id)})


class EditIOView(View):
	def post(self, request, id):
		form = IOForm(request.POST, instance=IOModel.objects.get(pk=id))
		if form.is_valid():
			io = form.save()
			io.save()
			return HttpResponseRedirect(request.session.pop('referer', reverse('registry:index')))
		else:
			return render(request, r'registry/edit_io.html', {'form': form, 'io_id': id})

	def get(self, request, id):
		form = IOForm(instance=IOModel.objects.get(pk=id))
		request.session['referer'] = request.META.get('HTTP_REFERER', reverse('registry:index'))
		return render(request, r'registry/edit_io.html', {'form': form, 'io_id': id})


class ReportView(View):
	def get(self, request):
		return render(request, r'registry/report.html')

class ReportViewView(View):
	def get(self, request):
		start_date = parse_date(request.GET.get('start_date'))
		end_date = parse_date(request.GET.get('end_date', str(datetime.date.today())))
		order_by = request.GET.get('order_by', 'registered')

		# TODO both above can be None, report only error in that case

		ios = IOModel.objects.filter(
			registered__gte=start_date,
			registered__lte=end_date
		).order_by(order_by)

		total = defaultdict(lambda: 0)
		category_transfers = defaultdict(lambda: defaultdict(lambda: 0))

		for io in ios:
			transfer_type = 'income' if io.type == IOModel.INCOME else 'outcome'

			total[transfer_type] += io.amount

			category_name = io.category.name if io.category is not None else '_inne_'
			separator_position = category_name.find(CategoryModel.NAMESPACE_SEPARATOR)
			while separator_position != -1:
				category_part = category_name[:separator_position]
				category_transfers[category_part][transfer_type] += io.amount
				separator_position = category_name.find(CategoryModel.NAMESPACE_SEPARATOR, separator_position + 1)
			category_transfers[category_name][transfer_type] += io.amount

		return render(
			request, r'registry/report_view.html',
			{
				'ios': ios,
				'start_date': start_date,
				'end_date': end_date,
				'total': total,
				'category_transfers': OrderedDict(sorted(category_transfers.items(), key=lambda item: item[0].lower)),
			}
		)

class BillingView(View):
	def get(self, request, id):
		billing = BillingCycleModel.objects.get(pk=id)
		report = OverviewReport(billing.start_date, billing.end_date)
		return render(request, r'registry/billing_view.html', {'name': billing.name, 'report': report})

src/registry/templates/registry/base.html
{% load staticfiles %}

<html>
<head>
    <title>Income/Outcome Registry</title>

    <link rel="stylesheet" href="{% static 'registry/jquery-ui-themes/themes/smoothness/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'registry/css/jquery.datetimepicker.min.css' %}">
    <link rel="stylesheet" href="{% static 'registry/base.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Audiowide&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Comfortaa&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Jura&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,500&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    {% block css %}{% endblock %}
    
    <script src="{% static 'registry/jquery.js' %}"></script>
    <script src="{% static 'registry/jquery.tablesorter.js' %}"></script>
    <script src="{% static 'registry/jquery-ui/jquery-ui.js' %}"></script>
    <script src="{% static 'registry/js/jquery.datetimepicker.full.min.js' %}"></script>
    <script src="{% static 'registry/js/jquery.cookie.js' %}"></script>
    {% block scripts %}{% endblock %}
</head>
<body>

{% block menu %}
<div id="mainmenu">
    <span><a href="{% url 'registry:index' %}">główna</a></span>
    <span><a href="{% url 'registry:billings' %}">rozliczenia</a></span>
    <span><a href="{% url 'registry:list_io' %}">wszystkie wydatki</a></span>
    <span><a href="{% url 'registry:report' %}">generator raportów</a></span>
</div>
{% endblock %}

<div id="content-wrapper">
    <div id="content">
    {% block content %}{% endblock %}
    </div>
</div>
</body>
</html>

src/registry/templates/registry/billing_view.html
{% extends 'registry/base.html' %}

{% load staticfiles %}

{% block scripts %}
<script language="javascript">
$(function() {

});
</script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'registry/report.css' %}">
{% endblock %}

{% block content %}
<div class="header">{{ name }}</div>
<div class="section">
    {{ report|default_if_none:'' }}
</div>
{% endblock %}

src/registry/templates/registry/billings.html
{% extends 'registry/base.html' %}

{% load staticfiles %}

{% block scripts %}
<script language="javascript">
$(document).ready(function() {
});
</script>
{% endblock %}  

{% block css %}
<link rel="stylesheet" href="{% static 'registry/report.css' %}">
<link rel="stylesheet" href="{% static 'registry/billings.css' %}">
{% endblock %}

{% block content %}
<div class="header">Ostatni raport</div>
{{ report|default_if_none:'' }}

<div class="header middle">Wszystkie raporty</div>
<div class="section">
    {% for billing in billings %}
        <div class="billing">
            <span class="name"><a href="{% url 'registry:billing/view' billing.id %}">{{ billing.name }}</a></span>
            <span class="dates">({{ billing.start_date }} - {{ billing.end_date|default_if_none:'dzisiaj' }})</span>
        </div>
    {% endfor %}
</div>

{% endblock %}

src/registry/templates/registry/delete_io.html
{% extends 'registry/base.html' %}

{% block content %}
<div style="text-align: center;">
    Czy jesteś pewna/pewien, że chcesz usunąć "{{ io.name }}"?<br/>
    <a href="{% url 'registry:delete_io' io.id %}?answer=yes">tak</a>
    /
    <a href="{% url 'registry:delete_io' io.id %}?answer=no">nie</a>
</div>
{% endblock %}

src/registry/templates/registry/edit_io.html
{% extends 'registry/base.html' %}

{% load staticfiles %}

{% block scripts %}
<script language="javascript">
$(function() {
    $('#id_registered').datepicker({dateFormat: "yy-mm-dd"});
});
</script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'registry/io_form.css' %}">
<link rel="stylesheet" href="{% static 'registry/io_list.css' %}">
{% endblock %}

{% block content %}
<form name="io" id="io" method="post" action="{% url 'registry:edit_io' io_id %}">
    {% csrf_token %}

    {% include "registry/io_form.html" %}
    
    <div><label></label><input type="submit" value="Zmień"></div>
</form>
{% endblock %}

src/registry/templates/registry/import.html
{% extends 'registry/base.html' %}

{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="{% static 'registry/io_list.css' %}">
<link rel="stylesheet" href="{% static 'registry/import.css' %}">
{% endblock %}

{% block scripts %}
<script src="{% static 'registry/import.js' %}"></script>
{% endblock %}

{% block content %}

{% if not error %}
    <table id="io_list">
        <thead>
        <tr>
            <th style="text-align:center"><input type="checkbox" id="check-all" checked /></th>
            <th>Data</th>
            <th>Kwota</th>
            <th>Kategoria</th>
            <th>Nazwa</th>
        </tr>
        </thead>
    {% for d in data %}
        <tbody>
        <tr class="{% cycle 'odd' 'even' %}">
            <td style="width:5%; text-align: center;"><input type="checkbox" checked id="check-{{ forloop.counter }}"/></td>
            <td name="date">{{ d.date|date:'Y-m-d' }}</td>
            <td name="amount">{{ d.amount }}</td>
            <td name="category">
                <select>
                    <option>---</option>
                    {% for category in categories %}
                        <option value="{{ category.id }}" {% if category.name == d.Categorizer__category %}selected{% endif %}>{{ category.name }}</option>
                    {% endfor %}
                </select>
            </td>
            <td name="description" style="width:60%;"><input type="text" value="{{ d.description }}" style="width: 100%"/></td>
        </tr>
        </tbody>
    {% endfor %}
    </table>

    <div id="button-import-wrapper">
        <input type="button" value="Zaimportuj" id="button-import"/>
    </div>
{% else %}
    <div class="error-message">{{ error }}</div>
{% endif %}

{% endblock %}

src/registry/templates/registry/index.html
{% extends 'registry/base.html' %}

{% load staticfiles %}

{% block scripts %}
<script language="javascript">
$(document).ready(function() {
    $('#id_registered').datetimepicker({
        timepicker: false,
        value: new Date(),
        format: 'Y-m-d'
    });
});
</script>
{% endblock %}  

{% block css %}
<link rel="stylesheet" href="{% static 'registry/io_form.css' %}">
<link rel="stylesheet" href="{% static 'registry/io_list.css' %}">
{% endblock %}

{% block content %}
<form name="io" id="io" method="post" action="{% url 'registry:index' %}">
    {% csrf_token %}

    {% include "registry/io_form.html" %}
    
    <div id="id_submit_div"><label></label><input type="submit" value="Dodaj"></div>
</form>

<form name="import" id="import" method="post" action="{% url 'registry:import' %}" enctype="multipart/form-data">
    {% csrf_token %}

    {{ import_form }}

    <div><label></label><input type="submit" value="Importuj"></div>
</form>

{% if ios %}
<div class="header middle">Ostatnio dodane</div>
{% include "registry/io_list.html" %}
{% endif %}

{% endblock %}

src/registry/templates/registry/io_form.html
<div>
    {{ form.name.errors }}
    <label for="{{ form.name.id_for_label }}">Nazwa:</label>{{ form.name }}
</div>

<div>
    {{ form.type.errors }}
    <label for="{{ form.type.id_for_label }}">Typ:</label>{{ form.type }}
</div>

<div>
    {{ form.amount.errors }}
    <label for="{{ form.amount.id_for_label }}">Kwota:</label>{{ form.amount }}    
</div>

<div>
    {{ form.registered.errors }}
    <label for="{{ form.registered.id_for_label }}">Data rozliczenia:</label>{{ form.registered }}
</div>

<div>
    {{ form.category.errors }}
    <label for="{{ form.category.id_for_label }}">Kategoria:</label>{{ form.category }}
</div>

<div>
    {{ form.payment_method.errors }}
    <label for="{{ form.payment_method.id_for_label }}">Płatność:</label>{{ form.payment_method }}
</div>

src/registry/templates/registry/io_list.html
{% load staticfiles %}

<table id="io_list">
<thead>
<tr>
    <th>Nazwa</th>
    <th>Typ</th>
    <th>Kwota</th>
    <th>Data rozliczenia</th>
    <th>Kategoria</th>
    <th>Płatność</th>
    <th colspan="2"></th>
</tr>
</thead>
<tbody>
{% for io in ios %}
<tr class="{% cycle 'odd' 'even' %}">
    <td style="width: 30%">{{ io.name }}</td>
    <td>{{ io.get_type_display }}</td>
    <td>{{ io.amount }}</td>
    <td>{{ io.registered|date:"d-m-Y" }}</td>
    <td>{{ io.category|default_if_none:"" }}</td>
    <td>{{ io.payment_method|default_if_none:"" }}</td>
    <td style="text-align: right; width: 20px;">        
        <a href="{% url 'registry:edit_io' io.id %}" title="edit"><img src="{% static 'registry/icons/edit.png' %}" alt="edit" /></a>
    </td>
    <td style="text-align: right; width: 20px;">
        <a href="{% url 'registry:delete_io' io.id %}" title="delete"><img src="{% static 'registry/icons/delete.png' %}" alt="delete" /></a>
    </td>
</tr>
{% endfor %}
</tbody>
</table>

src/registry/templates/registry/list_io.html
{% extends 'registry/base.html' %}

{% load staticfiles %}

{% block scripts %}
<script language="javascript">
$(document).ready(function() {
    $('#id_start_date').datetimepicker({
        timepicker: false,
        format: 'Y-m-d'
    });
    $('#id_end_date').datetimepicker({
        timepicker: false,
        defaultDate: new Date(),
        format: 'Y-m-d'
    });
    if ($('#id_end_date').val() == '')
    {
        $('#id_end_date').datetimepicker({value: new Date()});
    }
});
</script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'registry/io_list.css' %}">
<link rel="stylesheet" href="{% static 'registry/list_io.css' %}">
{% endblock %}

{% block content %}
<form id="io_list_filter" name="io_list_filter" action="{% url 'registry:list_io' %}" method="get">
    {% csrf_token %}
    {{ filter.form }}
    <input class="middle" type="submit" value="Filtruj" />
</form>
{% if ios %}
{% include "registry/io_list.html" %}

{% if ios.paginator.num_pages > 1 %}
<div id="paginator">
    {% if ios.has_previous %}
        <a href="?{{ query.urlencode }}&page=1" class="page_previous">&lt;&lt;</a>
        <a href="?{{ query.urlencode }}&page={{ ios.previous_page_number }}" class="page_previous">&lt;</a>
    {% endif %}
    
    <span class="current_page">{{ ios.number }} / {{ ios.paginator.num_pages }}</span>
    
    {% if ios.has_next %}
        <a href="?{{ query.urlencode }}&page={{ ios.next_page_number }}" class="page_next">&gt;</a>
        <a href="?{{ query.urlencode }}&page={{ ios.paginator.num_pages }}" class="page_next">&gt;&gt;</a>
    {% endif %}
</div>
{% endif %}

{% endif %}
{% endblock %}

src/registry/templates/registry/overview_report.html
<div class="section">
    <span class="label">Raport za:</span><span class="value">{{ report.start_date }} - {{ report.end_date }} ({{ report.closed|yesno:'zamknięty,otwarty' }})</span>
</div>

<div class="section">
    <div>Przychód:</div>
{% for income in report.incomes %}
    <div class="income"><span class="label">{{ income.name }}</span><span class="value">{{ income.amount }}</span></div>
{% endfor %}
</div>

<div class="section">
    <div>Rozchód per kategoria:</div>
{% for name, amount in report.categories.items %}
    <div class="income"><span class="label">{{ name }}</span><span class="value">{{ amount }}</span></div>
{% endfor %}
</div>

<div class="section">
    <div>Stałe wydatki:</div>
</div>

src/registry/templates/registry/report.html
{% extends 'registry/base.html' %}

{% load staticfiles %}

{% block scripts %}
<script language="javascript">
$(function() {
    $('#start_date').datetimepicker({
        timepicker: false,
        format: 'Y-m-d'
    });
    $('#end_date').datetimepicker({
        timepicker: false,
        value: new Date(),
        format: 'Y-m-d'
    });
});
</script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'registry/report_generator.css' %}">
{% endblock %}

{% block content %}
<form name="report" id="report" action="{% url 'registry:report_view' %}">
    <div>
        <label for="start_date">Od:</label><input type="date" id="start_date" name="start_date" />
        <label for="end_date">Do:</label><input type="date" id="end_date" name="end_date" />
        <input type="submit" value="Zobacz" />
    </div>
</form>
{% endblock %}

src/registry/templates/registry/report_view.html
{% extends 'registry/base.html' %}

{% load staticfiles %}
{% load mathfilters %}

{% block scripts %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'registry/report_view.css' %}">
<link rel="stylesheet" href="{% static 'registry/report.css' %}">
<link rel="stylesheet" href="{% static 'registry/io_list.css' %}">
{% endblock %}

{% block content %}
<div class="header first">Podsumowanie</div>

<div class="section">
    <span class="label">Raport za:</span><span class="value">{{ start_date }} - {{ end_date }}</span>
</div>

<div class="section">
    Ogółem:
    <span class="value income">+{{ total.income }}</span>
    <span class="value outcome">-{{ total.outcome }}</span>
    {% with total.income|sub:total.outcome as balance %}
        <span class="value {% if balance >= 0 %}income{% else %}outcome{% endif %}">{{ balance|sign }}</span>
    {% endwith %}
</div>

<div class="section">
<div>Rozliczenie per kategoria:</div>
{% for name, transfer in category_transfers.items %}
    <div>
        <span class="label">{{ name|default_if_none:'Brak kategorii' }}:</span>
        {% if transfer.income != 0 %}
            <span class="value income">+{{ transfer.income }}</span>
        {% endif %}
        {% if transfer.outcome != 0 %}
            <span class="value outcome">-{{ transfer.outcome }}</span>
        {% endif %}
        {% if transfer.income != 0 and transfer.outcome != 0 %}
            {% with transfer.income|sub:transfer.outcome as balance %}
                <span class="value {% if balance >= 0 %}income{% else %}outcome{% endif %}">{{ balance|sign }}</span>
            {% endwith %}
        {% endif %}
    </div>
{% endfor %}
</div>

{% if ios %}
<div class="header middle">Wydatki</div>
{% include "registry/io_list.html" %}
{% endif %}

{% endblock %}